name: DEV CI
on: [ push ]
jobs:
  build:
    name: Setting up CI environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Security check installed dependencies
        uses: symfonycorp/security-checker-action@v5

      - name: Tar it up
        run: tar -cvf setup.tar ./

      - name: Upload setup artifact
        uses: actions/upload-artifact@v3
        with:
          name: setup-artifact
          path: setup.tar

  fixer:
    name: PHP CS Fixer
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Setup Artifact
        uses: actions/download-artifact@v3
        with:
          name: setup-artifact

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Extraction
        run: tar -xvf setup.tar

      - name: Running PHP CS Fixer
        run: vendor/bin/php-cs-fixer fix --dry-run --diff

  phpstan:
    name: PHPStan Check
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Setup Artifact
        uses: actions/download-artifact@v3
        with:
          name: setup-artifact

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Extraction
        run: tar -xvf setup.tar

      - name: Running Phpstan
        run: vendor/bin/phpstan analyse -c phpstan.dist.neon

  testing:
    name: Tests
    runs-on: ubuntu-latest
    needs: build
    services:
      postgres:
        image: postgres:16.3
        env:
          POSTGRES_DB: symfony
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Download Setup Artifact
        uses: actions/download-artifact@v3
        with:
          name: setup-artifact

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Extraction
        run: tar -xvf setup.tar

      - name: Database migrations
        run: php bin/console doctrine:migrations:migrate --no-interaction
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/symfony

      - name: Load fixtures
        run: php bin/console --env=test doctrine:fixtures:load --purge-with-truncate --no-interaction
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/symfony

      - name: Execute tests via PHPUnit
        run: vendor/bin/phpunit --stop-on-failure
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/symfony
